version: '3.8'


networks:
  web-app-net:
    driver: bridge
services:
  mysql-service:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    networks:
      - web-app-net
    volumes:
      - ./mysql/data:/var/lib/mysql
  web-app:
    build: .
    container_name: bookshop-container
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    networks:
      - web-app-net




