version: '3.8'


networks:
  web-app-net:
    driver: bridge
services:
  mysql-service:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD=${{secrets.DB_PASSWORD}}
      MYSQL_DATABASE=bookshop
    networks:
      - web-app-net
    volumes:
      - ./mysql/data:/var/lib/mysql
  web-app:
    image: ${{secrets.DOCKERHUB_REGISTER}}/bookshop:latest
    container_name: bookshop-container
    ports:
      - "8082:8080"
    environment:
      DB_PASSWORD=${{secrets.DB_PASSWORD}}
      DB_USER=${{secrets.DB_USER}}
    networks:
      - web-app-net




